# Configuration application.properties 
spring.application.name=quizapp
spring.datasource.url=jdbc:mysql://localhost:3306/quiz_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4
spring.ai.openai.api-key=dummy-key

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Augmentez le timeout async à 2 minutes (120000ms)
spring.mvc.async.request-timeout=120000

# Configuration pour l'API
server.port=8080
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.open-in-view=false
logging.level.org.springframework.web=DEBUG

# JSON Configuration 
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false

#JWT
jwt.secret=QUIZAIapp@azerty123456789

# Gestion des sessions Hibernate
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Logs Hibernate pour debug
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Configuration de ai
deepseek.api.key=sk-fc3bdcd4578b4bf39ad9f14c37f4d918
deepseek.api.url=https://api.deepseek.com/v1/chat/completions
deepseek.api.timeout=90
deepseek.mock.enabled=true


#google 
GOOGLE_CLIENT_ID=345457357798-ojq3hgvenb95cph5fcjoquk22n9clbqv.apps.googleusercontent.com

#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abouzaidwijdane@gmail.com
spring.mail.password=tbil cpjs xwih dqeh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

